// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogLine.proto

package com.mhowlett;

public final class LogLineOuterClass {
  private LogLineOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogLineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mhowlett.LogLine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ip = 1;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 1;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string url = 3;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>string referer = 4;</code>
     * @return The referer.
     */
    java.lang.String getReferer();
    /**
     * <code>string referer = 4;</code>
     * @return The bytes for referer.
     */
    com.google.protobuf.ByteString
        getRefererBytes();

    /**
     * <code>string useragent = 5;</code>
     * @return The useragent.
     */
    java.lang.String getUseragent();
    /**
     * <code>string useragent = 5;</code>
     * @return The bytes for useragent.
     */
    com.google.protobuf.ByteString
        getUseragentBytes();

    /**
     * <code>.google.protobuf.UInt64Value session_id = 6;</code>
     * @return Whether the sessionId field is set.
     */
    boolean hasSessionId();
    /**
     * <code>.google.protobuf.UInt64Value session_id = 6;</code>
     * @return The sessionId.
     */
    com.google.protobuf.UInt64Value getSessionId();
    /**
     * <code>.google.protobuf.UInt64Value session_id = 6;</code>
     */
    com.google.protobuf.UInt64ValueOrBuilder getSessionIdOrBuilder();
  }
  /**
   * Protobuf type {@code com.mhowlett.LogLine}
   */
  public  static final class LogLine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mhowlett.LogLine)
      LogLineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogLine.newBuilder() to construct.
    private LogLine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogLine() {
      ip_ = "";
      url_ = "";
      referer_ = "";
      useragent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogLine();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogLine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              referer_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              useragent_ = s;
              break;
            }
            case 50: {
              com.google.protobuf.UInt64Value.Builder subBuilder = null;
              if (sessionId_ != null) {
                subBuilder = sessionId_.toBuilder();
              }
              sessionId_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(sessionId_);
                sessionId_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mhowlett.LogLineOuterClass.internal_static_com_mhowlett_LogLine_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mhowlett.LogLineOuterClass.internal_static_com_mhowlett_LogLine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mhowlett.LogLineOuterClass.LogLine.class, com.mhowlett.LogLineOuterClass.LogLine.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 1;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 1;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 2;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int URL_FIELD_NUMBER = 3;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 3;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 3;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERER_FIELD_NUMBER = 4;
    private volatile java.lang.Object referer_;
    /**
     * <code>string referer = 4;</code>
     * @return The referer.
     */
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referer_ = s;
        return s;
      }
    }
    /**
     * <code>string referer = 4;</code>
     * @return The bytes for referer.
     */
    public com.google.protobuf.ByteString
        getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERAGENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object useragent_;
    /**
     * <code>string useragent = 5;</code>
     * @return The useragent.
     */
    public java.lang.String getUseragent() {
      java.lang.Object ref = useragent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        useragent_ = s;
        return s;
      }
    }
    /**
     * <code>string useragent = 5;</code>
     * @return The bytes for useragent.
     */
    public com.google.protobuf.ByteString
        getUseragentBytes() {
      java.lang.Object ref = useragent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        useragent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSION_ID_FIELD_NUMBER = 6;
    private com.google.protobuf.UInt64Value sessionId_;
    /**
     * <code>.google.protobuf.UInt64Value session_id = 6;</code>
     * @return Whether the sessionId field is set.
     */
    public boolean hasSessionId() {
      return sessionId_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value session_id = 6;</code>
     * @return The sessionId.
     */
    public com.google.protobuf.UInt64Value getSessionId() {
      return sessionId_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : sessionId_;
    }
    /**
     * <code>.google.protobuf.UInt64Value session_id = 6;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getSessionIdOrBuilder() {
      return getSessionId();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(2, timestamp_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
      }
      if (!getRefererBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, referer_);
      }
      if (!getUseragentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, useragent_);
      }
      if (sessionId_ != null) {
        output.writeMessage(6, getSessionId());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
      }
      if (!getRefererBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, referer_);
      }
      if (!getUseragentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, useragent_);
      }
      if (sessionId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getSessionId());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mhowlett.LogLineOuterClass.LogLine)) {
        return super.equals(obj);
      }
      com.mhowlett.LogLineOuterClass.LogLine other = (com.mhowlett.LogLineOuterClass.LogLine) obj;

      if (!getIp()
          .equals(other.getIp())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!getReferer()
          .equals(other.getReferer())) return false;
      if (!getUseragent()
          .equals(other.getUseragent())) return false;
      if (hasSessionId() != other.hasSessionId()) return false;
      if (hasSessionId()) {
        if (!getSessionId()
            .equals(other.getSessionId())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + REFERER_FIELD_NUMBER;
      hash = (53 * hash) + getReferer().hashCode();
      hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUseragent().hashCode();
      if (hasSessionId()) {
        hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mhowlett.LogLineOuterClass.LogLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mhowlett.LogLineOuterClass.LogLine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mhowlett.LogLine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mhowlett.LogLine)
        com.mhowlett.LogLineOuterClass.LogLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mhowlett.LogLineOuterClass.internal_static_com_mhowlett_LogLine_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mhowlett.LogLineOuterClass.internal_static_com_mhowlett_LogLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mhowlett.LogLineOuterClass.LogLine.class, com.mhowlett.LogLineOuterClass.LogLine.Builder.class);
      }

      // Construct using com.mhowlett.LogLineOuterClass.LogLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ip_ = "";

        timestamp_ = 0L;

        url_ = "";

        referer_ = "";

        useragent_ = "";

        if (sessionIdBuilder_ == null) {
          sessionId_ = null;
        } else {
          sessionId_ = null;
          sessionIdBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mhowlett.LogLineOuterClass.internal_static_com_mhowlett_LogLine_descriptor;
      }

      @java.lang.Override
      public com.mhowlett.LogLineOuterClass.LogLine getDefaultInstanceForType() {
        return com.mhowlett.LogLineOuterClass.LogLine.getDefaultInstance();
      }

      @java.lang.Override
      public com.mhowlett.LogLineOuterClass.LogLine build() {
        com.mhowlett.LogLineOuterClass.LogLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mhowlett.LogLineOuterClass.LogLine buildPartial() {
        com.mhowlett.LogLineOuterClass.LogLine result = new com.mhowlett.LogLineOuterClass.LogLine(this);
        result.ip_ = ip_;
        result.timestamp_ = timestamp_;
        result.url_ = url_;
        result.referer_ = referer_;
        result.useragent_ = useragent_;
        if (sessionIdBuilder_ == null) {
          result.sessionId_ = sessionId_;
        } else {
          result.sessionId_ = sessionIdBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mhowlett.LogLineOuterClass.LogLine) {
          return mergeFrom((com.mhowlett.LogLineOuterClass.LogLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mhowlett.LogLineOuterClass.LogLine other) {
        if (other == com.mhowlett.LogLineOuterClass.LogLine.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getReferer().isEmpty()) {
          referer_ = other.referer_;
          onChanged();
        }
        if (!other.getUseragent().isEmpty()) {
          useragent_ = other.useragent_;
          onChanged();
        }
        if (other.hasSessionId()) {
          mergeSessionId(other.getSessionId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mhowlett.LogLineOuterClass.LogLine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mhowlett.LogLineOuterClass.LogLine) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 1;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 1;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 1;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 1;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 2;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 3;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 3;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 3;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 3;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object referer_ = "";
      /**
       * <code>string referer = 4;</code>
       * @return The referer.
       */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string referer = 4;</code>
       * @return The bytes for referer.
       */
      public com.google.protobuf.ByteString
          getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string referer = 4;</code>
       * @param value The referer to set.
       * @return This builder for chaining.
       */
      public Builder setReferer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        referer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string referer = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReferer() {
        
        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /**
       * <code>string referer = 4;</code>
       * @param value The bytes for referer to set.
       * @return This builder for chaining.
       */
      public Builder setRefererBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        referer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object useragent_ = "";
      /**
       * <code>string useragent = 5;</code>
       * @return The useragent.
       */
      public java.lang.String getUseragent() {
        java.lang.Object ref = useragent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          useragent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string useragent = 5;</code>
       * @return The bytes for useragent.
       */
      public com.google.protobuf.ByteString
          getUseragentBytes() {
        java.lang.Object ref = useragent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          useragent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string useragent = 5;</code>
       * @param value The useragent to set.
       * @return This builder for chaining.
       */
      public Builder setUseragent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        useragent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string useragent = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUseragent() {
        
        useragent_ = getDefaultInstance().getUseragent();
        onChanged();
        return this;
      }
      /**
       * <code>string useragent = 5;</code>
       * @param value The bytes for useragent to set.
       * @return This builder for chaining.
       */
      public Builder setUseragentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        useragent_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.UInt64Value sessionId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> sessionIdBuilder_;
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       * @return Whether the sessionId field is set.
       */
      public boolean hasSessionId() {
        return sessionIdBuilder_ != null || sessionId_ != null;
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       * @return The sessionId.
       */
      public com.google.protobuf.UInt64Value getSessionId() {
        if (sessionIdBuilder_ == null) {
          return sessionId_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : sessionId_;
        } else {
          return sessionIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      public Builder setSessionId(com.google.protobuf.UInt64Value value) {
        if (sessionIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sessionId_ = value;
          onChanged();
        } else {
          sessionIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      public Builder setSessionId(
          com.google.protobuf.UInt64Value.Builder builderForValue) {
        if (sessionIdBuilder_ == null) {
          sessionId_ = builderForValue.build();
          onChanged();
        } else {
          sessionIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      public Builder mergeSessionId(com.google.protobuf.UInt64Value value) {
        if (sessionIdBuilder_ == null) {
          if (sessionId_ != null) {
            sessionId_ =
              com.google.protobuf.UInt64Value.newBuilder(sessionId_).mergeFrom(value).buildPartial();
          } else {
            sessionId_ = value;
          }
          onChanged();
        } else {
          sessionIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      public Builder clearSessionId() {
        if (sessionIdBuilder_ == null) {
          sessionId_ = null;
          onChanged();
        } else {
          sessionId_ = null;
          sessionIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      public com.google.protobuf.UInt64Value.Builder getSessionIdBuilder() {
        
        onChanged();
        return getSessionIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      public com.google.protobuf.UInt64ValueOrBuilder getSessionIdOrBuilder() {
        if (sessionIdBuilder_ != null) {
          return sessionIdBuilder_.getMessageOrBuilder();
        } else {
          return sessionId_ == null ?
              com.google.protobuf.UInt64Value.getDefaultInstance() : sessionId_;
        }
      }
      /**
       * <code>.google.protobuf.UInt64Value session_id = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
          getSessionIdFieldBuilder() {
        if (sessionIdBuilder_ == null) {
          sessionIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                  getSessionId(),
                  getParentForChildren(),
                  isClean());
          sessionId_ = null;
        }
        return sessionIdBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mhowlett.LogLine)
    }

    // @@protoc_insertion_point(class_scope:com.mhowlett.LogLine)
    private static final com.mhowlett.LogLineOuterClass.LogLine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mhowlett.LogLineOuterClass.LogLine();
    }

    public static com.mhowlett.LogLineOuterClass.LogLine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogLine>
        PARSER = new com.google.protobuf.AbstractParser<LogLine>() {
      @java.lang.Override
      public LogLine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogLine(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogLine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogLine> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mhowlett.LogLineOuterClass.LogLine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mhowlett_LogLine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mhowlett_LogLine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rLogLine.proto\022\014com.mhowlett\032\036google/pr" +
      "otobuf/wrappers.proto\"\213\001\n\007LogLine\022\n\n\002ip\030" +
      "\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\004\022\013\n\003url\030\003 \001(\t\022\017\n" +
      "\007referer\030\004 \001(\t\022\021\n\tuseragent\030\005 \001(\t\0220\n\nses" +
      "sion_id\030\006 \001(\0132\034.google.protobuf.UInt64Va" +
      "lueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_com_mhowlett_LogLine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mhowlett_LogLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mhowlett_LogLine_descriptor,
        new java.lang.String[] { "Ip", "Timestamp", "Url", "Referer", "Useragent", "SessionId", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
